### ISSUE TITLE
Linux Compile

### ISSUE THREAD

**Issue by tomdolski** [TheGCCcoin/TheGCCcoin-source-code#3]
- Prepare code for Linux compilation with full instructions.

**Comment by pavik** [comment]
Instruction is here: https://github.com/TheGCCcoin/TheGCCcoin-source-code/blob/master/doc/build2-unix.txt. Existing instruction compiles wallet for dev machine only. If you plan distribute Linux wallet - create separate issue for that task and list Linux OS (and architectures: 32 or 64) that should be supported, binary compatibility between Linux OS is not working well - we have to test on each platform we want to support.
