### ISSUE TITLE
Fixing Donations

### ISSUE THREAD

**Issue by tomdolski** [TheGCCcoin/TheGCCcoin-source-code#4]
Noticed that donation doesn't work well regarding documentation. 
It needs to go 0,088% of sending the amount to the specific wallet address which will be later split into 3 different addresses by futures script. 

[ ]  Instead of 3 donations make one with 0,088% of each transaction which goes to wallet number: SCWSywQW6kgPcB5p5MrAGUS2qQkL5m6rDf

[ ] Please rename the variable from natureRecipient.address to sharingRecipient.address

[ ]  rename natureRecipient.amount to sharingRecipient.amount and fixed the amount to be 0,088% of transaction. All in all if sending 1 GCC coin it supposed to send donation to equal 0.00088 GCC, when sending 10 coins donation sending is 0.0088. Always 0,088% of transaction amount.

[ ] Make sure donation working on daemon and all compiles wallets as well.

**Comment by pavik** [comment]
As I see from the code donation is not implemented in the daemon, for now donation transaction is added only when user send money in the wallet. Here list of RPC commands https://github.com/TheGCCcoin/TheGCCcoin-source-code/blob/master/src/bitcoinrpc.cpp#L237. There are commands that allow to send money via RPC - they don't add donation transaction.

**Comment by pavik** [comment]
New version of Win and Mac wallets is available here: https://drive.google.com/open?id=0B0il7eoO84-sMHo5Ql9SbTVuNEU

**Comment by mrTall** [comment]
https://github.com/TheGCCcoin/TheGCCcoin-source-code/blob/master/src/rpcwallet.cpp#L308
Please check here, it looks like we have this function.
